### ISSUE TITLE
Errors in bootdqn_cartpole.py?

### ISSUE THREAD

**Issue by cubicgate** [kngwyu/Rainy#65]
Hi @kngwyu,

  When I ran your bootdqn_cartpole.py like this:
  
  python examples\bootdqn_cartpole.py train

I got:

  Traceback (most recent call last):
  File "examples\bootdqn_cartpole.py", line 21, in <module>
    ) -> Config:
  File "C:\rainy\cli.py", line 227, in decorator
    rainy_cli(obj=_CLIContext(f, agent, agent_selector, script_path))
  File "C:\Miniconda3\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "C:\Miniconda3\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "C:\Miniconda3\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Miniconda3\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Miniconda3\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "C:\Miniconda3\lib\site-packages\click\decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "C:\rainy\cli.py", line 52, in train
    experiment.train(eval_render=eval_render)
  File "C:\rainy\experiment.py", line 97, in train
    for res in self.ag.train_episodes(self.config.max_steps):
  File "C:\rainy\agents\base.py", line 274, in train_episodes
    self.store_transition(state, action, *transition[:-1])  # Do not pass info
TypeError: store_transition() takes 4 positional arguments but 6 were given

    Thanks for your help!

BTW:
I can run your dqn_cartpole.py like this:
python examples\dqn_cartpole.py train
with no problems.

**Comment by kngwyu** [comment]
Thank you, fixed by https://github.com/kngwyu/Rainy/commit/28a7ea53e577a9c209414b4fff3a22c6d8b530d0

**Comment by cubicgate** [comment]
Thanks @kngwyu  for your help!
